# k8s create nginx pod
apiVersion: v1
kind: Pod
metadata:
  name: bee

spec:
  containers:
    - name: bee-container
      image: nginx:latest
      ports:
        - containerPort: 80
  # spray=mortein:NoSchedule
  tolerations:
    - key: "spray"
      operator: "Equal"
      value: "mortein"
      effect: "NoSchedule"