# create node port service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: trainee-manibharathi
  labels:
    app: task-1
spec:
  type: NodePort
  selector:
    app: task-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001