apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod
  namespace: trainee-manibharathi
  labels:
    app: task-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-1
  template:
    metadata:
      name: nginx-pod
      labels:
        app: task-1
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80


# metadata:
#   name: nginx-pod
#   namespace: trainee-manibharathi
#   labels:
#     app: task-1
# spec:
#   containers:
#     - name: nginx-container
#       image: nginx:latest
#       ports:
#         - containerPort: 80
