apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: env-config-volume
          mountPath: /etc/env-config
      env:
        - name: ENV_VAR1
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: ENV_VAR1
        - name: ENV_VAR2
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: ENV_VAR2
  volumes:
    - name: config-volume
      configMap:
        name: my-configmap
        items:
          - key: file1.txt
            path: file1.txt
          - key: file2.txt
            path: file2.txt
    - name: env-config-volume
      configMap:
        name: my-configmap
        items:
          - key: ENV_VAR1
            path: ENV_VAR1.txt
          - key: ENV_VAR2
            path: ENV_VAR2.txt
