version: '3'

services:
  app1:
    build:
      context: ../Day1/Task1
    container_name: app1
    environment:
      - SERVER_NAME="app1"  # Corrected format
    networks:
      - app-network
  
  app2:
    build:
      context: ../Day1/Task1
    container_name: app2
    environment:
      - SERVER_NAME="app2"  # Corrected format
    networks:
      - app-network
  
  app3:
    build:
      context: ../Day1/Task1
    container_name: app3
    environment:
      - SERVER_NAME="app3"  # Corrected format
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./Proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      # - app2
      # - app3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge