version: '3.8'

services:
  web:
    build: .
    container_name: my_web_app
    ports:
      - "443:6000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/my_database
      - PORT = 6000
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: my_mongo_db
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
