version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/my_database
      - PORT = 6000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://${api}:5000
    depends_on:
      - api

volumes:
  mongo_data:
