# Use the official Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the application code to the container
COPY . /app

# Install dependencies
RUN pip install Flask

ENV SERVER_NAME "Default"

# Expose the port
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]
