services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public
      - private
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./Frontend
    networks:
      - private
    deploy:
      replicas: 1

  backend:
    build: ./Backend
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: exampledb
      PORT: 5000
    networks:
      - private
    deploy:
      replicas: 2

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - private

networks:
  public:
    driver: bridge

  private:
    driver: bridge
    internal: true

  
