apiVersion: v1
kind: Pod
metadata:
  name: getpod-nodeinfo
  namespace: trainee-manibharathi
spec:
  serviceAccountName: kgetonly-sa
  containers:
  - name: check-value
    image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "cat /mnt/zone-annotation.txt"
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    volumeMounts:
    - name: nodeinfo
      mountPath: /mnt
  initContainers:  # Corrected field name
  - name: init-getpod-nodeinfo
    image: bitnami/kubectl:1.31.3-debian-12-r1
    command:
      - /bin/sh
      - -c
      - |
        NODE_NAME=$(kubectl get pod $(hostname) -o=jsonpath='{.spec.nodeName}')
        kubectl get node $NODE_NAME -o=jsonpath='{.metadata.labels.topology\.kubernetes\.io/zone}' > /mnt/zone-annotation.txt
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    volumeMounts:
    - name: nodeinfo
      mountPath: /mnt
  volumes:
  - name: nodeinfo
    emptyDir: {}
