apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kgetonly-cr
  namespace: trainee-manibharathi
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
