FROM jenkins/jenkins:lts

# Install Docker CLI
USER root
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Add Jenkins to Docker group
RUN usermod -aG docker jenkins

USER jenkins
