apiVersion: apps/v1
kind: Deployment
metadata:
  name: day4-task1-deployment
  labels:
    app: day4-task1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: day4-task1
  template:
      metadata:
        labels:
          app: day4-task1
      spec:
        containers:
          - name: nginx
            image: nginx:latest
            ports:
              - containerPort: 80
            volumeMounts:
              - name: html-code-volume
                mountPath: /usr/share/nginx/html
        initContainers:
          - name: git-clone
            image: alpine/git:latest
            command:
              - /bin/sh
              - -c
              - |
                git clone https://github.com/itsmanibharathi/demo-html /tmp/html-code
                cp -r /tmp/html-code/* /mnt/html
            volumeMounts:
              - name: html-code-volume
                mountPath: /mnt/html
        volumes:
          - name: html-code-volume
            emptyDir: {}
          