server:
  http_listen_port: 9080
  grpc_listen_port: 9095

clients:
  - url: http://loki:3100/api/prom/push  # Loki container URL

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: proxy-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: proxy
          __path__: /var/log/nginx/*.log  # Path to Nginx logs

  - job_name: backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          __path__: /var/log/backend/*.log  # Path to backend logs